name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: bash ./gradlew assembleGithub
    - name: Upload Pre-Release Apk
      uses: actions/upload-artifact@v3
      with:
        name: Pre-Release Apk
        path: app/build/outputs/apk/Github/release/*.apk
